version: '3'

services:
  detector-app:
    networks:
      - detector
    container_name: detector-app
    build:
      context: ./detector-app/
      dockerfile: Dockerfile
    ports: 
      - '4200:4200'
    depends_on:
      - detector-api

  detector-api:
    networks:
      - detector
    container_name: detector-api
    build:
      context: ./detector-api
      dockerfile: Dockerfile
    ports:
      - '8001:8001'
    environment:
      - NODE_CONFIG={
          "tf_serving":{
            "host":"detector-model-serving"
          },
          "mock":{
            "tf_serving_client":false
          }
        }
      - NODE_ENV=docker
    depends_on:
      - detector-model-serving

  detector-model-serving:
    networks:
      - detector
    container_name: detector-model-serving
    build:
      context: ./model_serving
      dockerfile: Dockerfile
    ports:
      - '9000:9000'

networks:
  detector:
    driver: bridge
