version: '2.3'

services:
  detector-app:
    networks:
      - detector
    container_name: detector-app
    build:
      context: ./detector-app/
      dockerfile: Dockerfile
    ports: 
      - '80:80'
    depends_on:
      - detector-api

  detector-api:
    networks:
      - detector
    container_name: detector-api
    build:
      context: ./detector-api
      dockerfile: Dockerfile
    ports:
      - '8001:8001'
    environment:
      - NODE_CONFIG={
          "tf_serving":{
            "host":"detector-model-serving"
          },
          "mock":{
            "tf_serving_client":false
          }
        }
      - NODE_ENV=docker
    depends_on:
      - detector-model-serving

  detector-model-serving:
    networks:
      - detector
    container_name: detector-model-serving
    runtime: nvidia
    build:
      context: ./model_serving
      dockerfile: Dockerfile.gpu
    ports:
      - '9000:9000'
      - '8501:8501'
  
networks:
  detector:
    driver: bridge
