version: '3'

services:
  detector-app:
    networks:
      - detector
    container_name: detector-app
    build:
      context: ./detector-app/
      dockerfile: Dockerfile
    ports: 
      - '80:80'
    depends_on:
      - cors-anywhere

  detector-model-serving:
    networks:
      - detector
    container_name: detector-model-serving
    build:
      context: ./model_serving
      dockerfile: Dockerfile.TF.Latest
    ports:
      - '9000:9000'
      - '8501:8501'

  cors-anywhere:
    networks:
      - detector
    container_name: cors-anywhere
    build:
      context: ./cors-anywhere
      dockerfile: Dockerfile
    ports:
      - '9501:9501'
    depends_on:
      - detector-model-serving
  
networks:
  detector:
    driver: bridge
